  # List of processes by name to track through falco.
- list: tracking_processes
  items: [
    apache2
    ]

# List of deemed harmless system calls to ignore during monitoring.
# Alphabetized for easy editing.
- list: ignored_syscalls
  items: [
    acct, adjtimex, bdflush, cachestat, capget, clock_adjtime, 
    clock_getres, clock_gettime, clock_nanosleep, clock_settime,
    epoll_create, epoll_create1, epoll_ctl, epoll_ctl_old, epoll_pwait, 
    epoll_pwait2, epoll_wait, epoll_wait_old, fadvise64, fanotify_init, 
    fgetxattr, flistxattr, fstat, fstat64, fstatat64, fstatfs, fstatfs64, 
    futex_requeue, futex_wait, futex_waitv, futex_wake, futimesat, getcpu, 
    getcwd, getdents, getdents64, getegid, geteuid, getgid, getgroups, 
    getitimer, getpeername, getpgid, getpgrp, getpid, getpmsg, getppid, 
    getpriority, getrandom, getresgid, getresuid, getrlimit, getrusage, 
    getsid,getsockname, getsockopt, gettid, gettimeofday, getuid, getxattr, 
    getxattrat, get_kernel_syms, get_mempolicy, get_robust_list, get_thread_area, 
    inotify_add_watch, inotify_init, inotify_init1, inotify_rm_watch, ioprio_get, 
    io_getevents, io_pgetevents, ipc, kcmp, lgetxattr, listmount, listxattr, 
    listxattrat, llistxattr, llseek, lookup_dcookie, lseek, lsm_get_self_attr, 
    lsm_list_modules, lstat, lstat64, madvise, mincore, mq_getsetattr, mq_notify, 
    mq_timedreceive, mq_timedsend, msgget, multiplexer, nanosleep, newfstatat, oldfstat, 
    oldlstat, oldolduname, oldstat, olduname, pciconfig_iobase, personality, poll, ppoll, 
    process_madvise, pselect6, query_module, readlink, readlinkat, riscv_hwprobe, 
    sched_getaffinity, sched_getattr, sched_getparam, sched_getscheduler, sched_
    get_priority_max, sched_get_priority_min, sched_rr_get_interval, sched_setaffinity, 
    sched_yield, select, setdomainname, setitimer, settimeofday, sgetmask, shmget, 
    stat, stat64, statfs, statfs6, statx, stime, sysinfo, syslog, sys_debug_setcontext, 
    time, timerfd, timerfd_create, timerfd_gettime, timer_create, timer_delete, 
    timer_getoverrun, timer_gettime, timer_settime, times, umask, uname, 
    uretprobe, ustat, utime, utimensat, utimes, wait4, waitid, waitpid, _newselect
    ]

# List of events to ignore in falco tracing.
- list: ignored_events
  items: [
    switch, signaldeliver, page_fault
    ]

- macro: is_tracking_process
  condition: (proc.name in (tracking_processes))

- macro: is_syscall_harmless
  condition: (not syscall.type in (ignored_syscalls))

- macro: is_loud_event
  condition: (not evt.type in (ignored_events)) 

# Final rule to monitor all processes in tracking_processes who call system calls not in the ignored_syscalls list or 
# ignored_events list.
- rule: Process system call monitor
  desc: Monitor activity on tracking_processes
  condition: (is_tracking_process) and (is_syscall_harmless) and (is_loud_event)
  output: Name:%proc.name, FD:%fd.num, Syscall:%syscall.type, Args:%evt.args, Return:%evt.rawres, PID:%proc.pid
  priority: info
  tags: [syscalls]